Codebook

Codebook was generated on 25-09-2016.

Variables and their summary
1. Subject : unique ID of subject who performs the actvity, ID range from 1 to 30.
2. activity : ID for activity, and names for activities are given in the file activity_labels.txt
3. Domain : domain of the activity, like time , frequence.
4. Sensor : sensors like gyroscope, accelerometer
5. vVariable : mean and Standard Deviation
6. Jerk : Jerk signal
7. Magnitude : magnitude of the signals


Structure
str(tidydata)
```
##'data.frame':	180 obs. of  68 variables:
##$ subject                               : int  1 1 1 1 1 1 2 2 2 2 ...
## $ activity                              : int  1 2 3 4 5 6 1 2 3 4 ...
## $ tBodyAccelerometer-mean()-X           : num  0.277 0.255 0.289 0.261 0.279 ...
## $ tBodyAccelerometer-mean()-Y           : num  -0.01738 -0.02395 -0.00992 -0.00131 -0.01614 ...
## $ tBodyAccelerometer-mean()-Z           : num  -0.1111 -0.0973 -0.1076 -0.1045 -0.1106 ...
## $ tBodyAccelerometer-std()-X            : num  -0.284 -0.355 0.03 -0.977 -0.996 ...
## $ tBodyAccelerometer-std()-Y            : num  0.11446 -0.00232 -0.03194 -0.92262 -0.97319 ...
## $ tBodyAccelerometer-std()-Z            : num  -0.26 -0.0195 -0.2304 -0.9396 -0.9798 ...
## $ tGravityAccelerometer-mean()-X        : num  0.935 0.893 0.932 0.832 0.943 ...
## $ tGravityAccelerometer-mean()-Y        : num  -0.282 -0.362 -0.267 0.204 -0.273 ...
## $ tGravityAccelerometer-mean()-Z        : num  -0.0681 -0.0754 -0.0621 0.332 0.0135 ...
## $ tGravityAccelerometer-std()-X         : num  -0.977 -0.956 -0.951 -0.968 -0.994 ...
## $ tGravityAccelerometer-std()-Y         : num  -0.971 -0.953 -0.937 -0.936 -0.981 ...
## $ tGravityAccelerometer-std()-Z         : num  -0.948 -0.912 -0.896 -0.949 -0.976 ...
## $ tBodyAccelerometerJerk-mean()-X       : num  0.074 0.1014 0.0542 0.0775 0.0754 ...
## $ tBodyAccelerometerJerk-mean()-Y       : num  0.028272 0.019486 0.02965 -0.000619 0.007976 ...
## $ tBodyAccelerometerJerk-mean()-Z       : num  -0.00417 -0.04556 -0.01097 -0.00337 -0.00369 ...
## $ tBodyAccelerometerJerk-std()-X        : num  -0.1136 -0.4468 -0.0123 -0.9864 -0.9946 ...
## $ tBodyAccelerometerJerk-std()-Y        : num  0.067 -0.378 -0.102 -0.981 -0.986 ...
## $ tBodyAccelerometerJerk-std()-Z        : num  -0.503 -0.707 -0.346 -0.988 -0.992 ...
## $ tBodyGyroscope-mean()-X               : num  -0.0418 0.0505 -0.0351 -0.0454 -0.024 ...
## $ tBodyGyroscope-mean()-Y               : num  -0.0695 -0.1662 -0.0909 -0.0919 -0.0594 ...
```

Key variables

 key(tidydata)
 ```
## [1] "subject"          "activity"         "featDomain"      
## [4] "featAcceleration" "featInstrument"   "featJerk"        
## [7] "featMagnitude"    "featVariable"     "featAxis"
```

Few rows of Dataset
head(tidydata)

subject activity tBodyAccelerometer-mean()-X tBodyAccelerometer-mean()-Y tBodyAccelerometer-mean()-Z
1         1        1                   0.2773308                -0.017383819                  -0.1111481
31        1        2                   0.2554617                -0.023953149                  -0.0973020
61        1        3                   0.2891883                -0.009918505                  -0.1075662
91        1        4                   0.2612376                -0.001308288                  -0.1045442
121       1        5                   0.2789176                -0.016137590                  -0.1106018
151       1        6                   0.2215982                -0.040513953                  -0.1132036
    tBodyAccelerometer-std()-X tBodyAccelerometer-std()-Y tBodyAccelerometer-std()-Z
1                  -0.28374026                0.114461337                -0.26002790
31                 -0.35470803               -0.002320265                -0.01947924
61                  0.03003534               -0.031935943                -0.23043421
91                 -0.97722901               -0.922618642                -0.93958629
121                -0.99575990               -0.973190056                -0.97977588
151                -0.92805647               -0.836827406                -0.82606140
    tGravityAccelerometer-mean()-X tGravityAccelerometer-mean()-Y tGravityAccelerometer-mean()-Z
1                        0.9352232                     -0.2821650                    -0.06810286
31                       0.8933511                     -0.3621534                    -0.07540294
61                       0.9318744                     -0.2666103                    -0.06211996
91                       0.8315099                      0.2044116                     0.33204370
121                      0.9429520                     -0.2729838                     0.01349058
151                     -0.2488818                      0.7055498                     0.44581772
    tGravityAccelerometer-std()-X tGravityAccelerometer-std()-Y tGravityAccelerometer-std()-Z
1                      -0.9766096                    -0.9713060                    -0.9477172
31                     -0.9563670                    -0.9528492                    -0.9123794
61                     -0.9505598                    -0.9370187                    -0.8959397
91                     -0.9684571                    -0.9355171                    -0.9490409
121                    -0.9937630                    -0.9812260                    -0.9763241
151                    -0.8968300                    -0.9077200                    -0.8523663
    tBodyAccelerometerJerk-mean()-X tBodyAccelerometerJerk-mean()-Y tBodyAccelerometerJerk-mean()-Z
1                        0.07404163                    0.0282721096                    -0.004168406
31                       0.10137273                    0.0194863076                    -0.045562545
61                       0.05415532                    0.0296504490                    -0.010971973
91                       0.07748252                   -0.0006191028                    -0.003367792
121                      0.07537665                    0.0079757309                    -0.003685250
151                      0.08108653                    0.0038382040                     0.010834236
    tBodyAccelerometerJerk-std()-X tBodyAccelerometerJerk-std()-Y tBodyAccelerometerJerk-std()-Z
1                      -0.11361560                      0.0670025                     -0.5026998
31                     -0.44684389                     -0.3782744                     -0.7065935
61                     -0.01228386                     -0.1016014                     -0.3457350
91                     -0.98643071                     -0.9813720                     -0.9879108
121                    -0.99460454                     -0.9856487                     -0.9922512
151                    -0.95848211                     -0.9241493                     -0.9548551
    tBodyGyroscope-mean()-X tBodyGyroscope-mean()-Y tBodyGyroscope-mean()-Z tBodyGyroscope-std()-X
1               -0.04183096             -0.06953005              0.08494482             -0.4735355
31               0.05054938             -0.16617002              0.05835955             -0.5448711
61              -0.03507819             -0.09093713              0.09008501             -0.4580305
91              -0.04535006             -0.09192415              0.06293138             -0.9772113
121             -0.02398773             -0.05939722              0.07480075             -0.9871919
151             -0.01655309             -0.06448612              0.14868944             -0.8735439
    tBodyGyroscope-std()-Y tBodyGyroscope-std()-Z tBodyGyroscopeJerk-mean()-X
1             -0.054607769             -0.3442666                 -0.08999754
31             0.004105184             -0.5071687                 -0.12223277
61            -0.126349195             -0.1247025                 -0.07395920
91            -0.966473895             -0.9414259                 -0.09367938
121           -0.987734440             -0.9806456                 -0.09960921
151           -0.951090440             -0.9082847                 -0.10727095
    tBodyGyroscopeJerk-mean()-Y tBodyGyroscopeJerk-mean()-Z tBodyGyroscopeJerk-std()-X
1                   -0.03984287                 -0.04613093                 -0.2074219
31                  -0.04214859                 -0.04071255                 -0.6147865
61                  -0.04399028                 -0.02704611                 -0.4870273
91                  -0.04021181                 -0.04670263                 -0.9917316
121                 -0.04406279                 -0.04895055                 -0.9929451
151                 -0.04151729                 -0.07405012                 -0.9186085
    tBodyGyroscopeJerk-std()-Y tBodyGyroscopeJerk-std()-Z tBodyAccelerometerMagnitude-mean()
1                   -0.3044685                 -0.4042555                        -0.13697118
31                  -0.6016967                 -0.6063320                        -0.12992763
61                  -0.2388248                 -0.2687615                         0.02718829
91                  -0.9895181                 -0.9879358                        -0.94853679
121                 -0.9951379                 -0.9921085                        -0.98427821
151                 -0.9679072                 -0.9577902                        -0.84192915
    tBodyAccelerometerMagnitude-std() tGravityAccelerometerMagnitude-mean()
1                         -0.21968865                           -0.13697118
31                        -0.32497093                           -0.12992763
61                         0.01988435                            0.02718829
91                        -0.92707842                           -0.94853679
121                       -0.98194293                           -0.98427821
151                       -0.79514486                           -0.84192915
    tGravityAccelerometerMagnitude-std() tBodyAccelerometerJerkMagnitude-mean()
1                            -0.21968865                            -0.14142881
31                           -0.32497093                            -0.46650345
61                            0.01988435                            -0.08944748
91                           -0.92707842                            -0.98736420
121                          -0.98194293                            -0.99236779
151                          -0.79514486                            -0.95439626
    tBodyAccelerometerJerkMagnitude-std() tBodyGyroscopeMagnitude-mean() tBodyGyroscopeMagnitude-std()
1                             -0.07447175                    -0.16097955                    -0.1869784
31                            -0.47899162                    -0.12673559                    -0.1486193
61                            -0.02578772                    -0.07574125                    -0.2257244
91                            -0.98412002                    -0.93089249                    -0.9345318
121                           -0.99309621                    -0.97649379                    -0.9786900
151                           -0.92824563                    -0.87475955                    -0.8190102
    tBodyGyroscopeJerkMagnitude-mean() tBodyGyroscopeJerkMagnitude-std() fBodyAccelerometer-mean()-X
1                           -0.2987037                        -0.3253249                 -0.20279431
31                          -0.5948829                        -0.6485530                 -0.40432178
61                          -0.2954638                        -0.3065106                  0.03822918
91                          -0.9919763                        -0.9883087                 -0.97964124
121                         -0.9949668                        -0.9947332                 -0.99524993
151                         -0.9634610                        -0.9358410                 -0.93909905
    fBodyAccelerometer-mean()-Y fBodyAccelerometer-mean()-Z fBodyAccelerometer-std()-X
1                   0.089712726                  -0.3315601                -0.31913472
31                 -0.190976721                  -0.4333497                -0.33742819
61                  0.001549908                  -0.2255745                 0.02433084
91                 -0.944084550                  -0.9591849                -0.97641231
121                -0.977070848                  -0.9852971                -0.99602835
151                -0.867065205                  -0.8826669                -0.92443743
    fBodyAccelerometer-std()-Y fBodyAccelerometer-std()-Z fBodyAccelerometerJerk-mean()-X
1                   0.05604001                -0.27968675                     -0.17054696
31                  0.02176951                 0.08595655                     -0.47987525
61                 -0.11296374                -0.29792789                     -0.02766387
91                 -0.91727501                -0.93446956                     -0.98659702
121                -0.97229310                -0.97793726                     -0.99463080
151                -0.83362556                -0.81289156                     -0.95707388
    fBodyAccelerometerJerk-mean()-Y fBodyAccelerometerJerk-mean()-Z fBodyAccelerometerJerk-std()-X
1                       -0.03522552                      -0.4689992                     -0.1335866
31                      -0.41344459                      -0.6854744                     -0.4619070
61                      -0.12866716                      -0.2883347                     -0.0863279
91                      -0.98157947                      -0.9860531                     -0.9874930
121                     -0.98541870                      -0.9907522                     -0.9950738
151                     -0.92246261                      -0.9480609                     -0.9641607
    fBodyAccelerometerJerk-std()-Y fBodyAccelerometerJerk-std()-Z fBodyGyroscope-mean()-X
1                        0.1067399                     -0.5347134              -0.3390322
31                      -0.3817771                     -0.7260402              -0.4926117
61                      -0.1345800                     -0.4017215              -0.3524496
91                      -0.9825139                     -0.9883392              -0.9761615
121                     -0.9870182                     -0.9923498              -0.9863868
151                     -0.9322179                     -0.9605870              -0.8502492
    fBodyGyroscope-mean()-Y fBodyGyroscope-mean()-Z fBodyGyroscope-std()-X fBodyGyroscope-std()-Y
1               -0.10305942             -0.25594094             -0.5166919            -0.03350816
31              -0.31947461             -0.45359721             -0.5658925             0.15153891
61              -0.05570225             -0.03186943             -0.4954225            -0.18141473
91              -0.97583859             -0.95131554             -0.9779042            -0.96234504
121             -0.98898446             -0.98077312             -0.9874971            -0.98710773
151             -0.95219149             -0.90930272             -0.8822965            -0.95123205
    fBodyGyroscope-std()-Z fBodyAccelerometerMagnitude-mean() fBodyAccelerometerMagnitude-std()
1               -0.4365622                        -0.12862345                        -0.3980326
31              -0.5717078                        -0.35239594                        -0.4162601
61              -0.2384436                         0.09658453                        -0.1865303
91              -0.9439178                        -0.94778292                        -0.9284448
121             -0.9823453                        -0.98535636                        -0.9823138
151             -0.9165825                        -0.86176765                        -0.7983009
    fBodyAccelerometerJerkMagnitude-mean() fBodyAccelerometerJerkMagnitude-std()
1                              -0.05711940                            -0.1034924
31                             -0.44265216                            -0.5330599
61                              0.02621849                            -0.1040523
91                             -0.98526213                            -0.9816062
121                            -0.99254248                            -0.9925360
151                            -0.93330036                            -0.9218040
    fBodyGyroscopeMagnitude-mean() fBodyGyroscopeMagnitude-std() fBodyGyroscopeJerkMagnitude-mean()
1                       -0.1992526                    -0.3210180                         -0.3193086
31                      -0.3259615                    -0.1829855                         -0.6346651
61                      -0.1857203                    -0.3983504                         -0.2819634
91                      -0.9584356                    -0.9321984                         -0.9897975
121                     -0.9846176                    -0.9784661                         -0.9948154
151                     -0.8621902                    -0.8243194                         -0.9423669
    fBodyGyroscopeJerkMagnitude-std()
1                          -0.3816019
31                         -0.6939305
61                         -0.3919199
91                         -0.9870496
121                        -0.9946711
151                        -0.9326607

